FROM node:10 as builder
WORKDIR /usr/src/app

COPY frontend/package.json ./package.json

RUN npm install

COPY frontend .

RUN npm run build

FROM nginx:alpine

COPY --from=builder /usr/src/app/dist /var/www/public

COPY nginx/conf.d/differences-proccessor.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]